nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Architecture:
      - Addon Lifecycle: addon-lifecycle.md
      - Mod Architecture: mod-architecture.md
  - Addon Development: addon-development.md
  - Addon Example: addon-example.md

site_name: ZP3 API 0.2a